language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.3
    - android-26
    - sys-img-armeabi-v7a-android-26
